name: 'WordPress Maintenence Upgrade'
description: 'Github action with tools to help with WordPress upgrades.'
inputs:
  ignoreGitChanges:
    description: 'Ignore git changes'
    required: false
    default: false
  pluginDirectory:
    description: 'Relative path to plugins'
    required: false
    default: 'test/wordpress/wp-content/plugins'
  databaseName:
    description: 'Database name'
    required: false
    default: 'wordpress'
  databaseUsername:
    description: 'Database username'
    required: false
    default: 'root'
  databasePassword:
    description: 'Database password'
    required: false
    default: 'root'
  wordPressPath:
    description: 'Relative path to directory where WordPress is installed'
    required: false
    default: false
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
