name: 'WordPress Maintenence Upgrade'
description: 'Github action with tools to help with WordPress upgrades.'
inputs:
  
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
