name: Maintenance Updates

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}

      DB_DATABASE: wordpress
      DB_USER: root
      DB_PASSWORD: root

      WP_SITE_URL: wordpress-github-actions-testing.ddev.site
      WP_SITE_TITLE: "Devops Site"
      WP_ADMIN_USERNAME: admin
      WP_ADMIN_EMAIL: admin@example.com

      PLUGIN_DIRECTORY: wp-content/plugins
      THEME_DIRECTORY: wp-content/themes
      LANGUAGE_DIRECTORY: wp-content/languages

      # Detemines whether ACF pro should be updated.
      UPDATE_ACF_PRO: false
      UPDATE_LANGUAGES: true
    defaults:
      run:
        shell: bash
        working-directory: test/wordpress
    steps:
      - uses: actions/checkout@v3

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          sudo mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
        env:
          update: true

      - name: Install WP CLI
        run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

      - name: Install and Configure WordPress
        run: |
          php wp-cli.phar core download --force --version=6.1.1
          php wp-cli.phar config create --force --dbname=${{ env.DB_DATABASE }} --dbuser=${{ env.DB_USER }} --dbpass=${{ env.DB_PASSWORD }}
          php wp-cli.phar core install --url=${{ env.WP_SITE_URL}} --title="${{env.WP_SITE_TITLE}}" --admin_user=${{ env.WP_ADMIN_USERNAME }} --admin_email=${{ env.WP_ADMIN_EMAIL }}

      - name: Install out of date plugins
        run: |
          php wp-cli.phar plugin install bbpress --version=2.5.13
          php wp-cli.phar plugin install advanced-custom-fields --version=6.0.7

      - name: Cleanup
        run:
          rm wp-cli.phar
          rm wp-config.php
          sudo mysql -e 'DROP DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          sudo mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Run the action.
        uses: ./
        with:
          wordPressPath: test/wordpress
